// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPyqq8p-01ydasCXwascv8KMkZqmPrhW0',
    appId: '1:237523947990:web:0049aec147179000411477',
    messagingSenderId: '237523947990',
    projectId: 'fluttertp-d33a9',
    authDomain: 'fluttertp-d33a9.firebaseapp.com',
    storageBucket: 'fluttertp-d33a9.firebasestorage.app',
    measurementId: 'G-X6H3M3Z8VL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDC_8oIzvdStfU_gz-DoyTEUOHjNRoJvTo',
    appId: '1:237523947990:android:236467f7dff83607411477',
    messagingSenderId: '237523947990',
    projectId: 'fluttertp-d33a9',
    storageBucket: 'fluttertp-d33a9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYId9QGLi-yyBR1dNIPhmdTuCUbKK1wJ8',
    appId: '1:237523947990:ios:c9b3ee4874dc6b0a411477',
    messagingSenderId: '237523947990',
    projectId: 'fluttertp-d33a9',
    storageBucket: 'fluttertp-d33a9.firebasestorage.app',
    iosBundleId: 'com.example.fluttertp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYId9QGLi-yyBR1dNIPhmdTuCUbKK1wJ8',
    appId: '1:237523947990:ios:c9b3ee4874dc6b0a411477',
    messagingSenderId: '237523947990',
    projectId: 'fluttertp-d33a9',
    storageBucket: 'fluttertp-d33a9.firebasestorage.app',
    iosBundleId: 'com.example.fluttertp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPyqq8p-01ydasCXwascv8KMkZqmPrhW0',
    appId: '1:237523947990:web:86af0685e4af198a411477',
    messagingSenderId: '237523947990',
    projectId: 'fluttertp-d33a9',
    authDomain: 'fluttertp-d33a9.firebaseapp.com',
    storageBucket: 'fluttertp-d33a9.firebasestorage.app',
    measurementId: 'G-20JBQQ2PPL',
  );
}
